mutation LOGIN($data: LoginInput!) {
    login(data: $data) {
        token
        userId
    }
}

# variables

# {
#   "data": {
#     "userName": "brunohubner",
#     "password": "dev12345"
#   }
# }
